apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.24.0
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh
    version: 0.21.1
    # repository: oci://quay.io/codefresh/dev
    # version: 25.11-0-f9a04a1  
    # repository: oci://quay.io/codefresh/dev
    # version: 0.0.0-baabd74
