apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.24.0
dependencies:
  - name: gitops-runtime
    # repository: oci://quay.io/codefresh
    # version: 0.25.0
    repository: oci://quay.io/codefresh/dev
    version: 0.25.1-prep-v0.25.1-2cb97f3  
    # repository: oci://quay.io/codefresh/dev
    # version: 0.0.0-baabd74
